export const SET_STATUS_FILTER = 'SET_STATUS_FILTER';
export const Status = {
	STATUS_DEV: 'DEVELOPMENT',
	STATUS_PROD: 'FINAL VERSION',
	STATUS_QA: 'TESTING VERSION'
}

export const SET_INSTANCES = "SET_INSTANCES";

export const INSTANCE_LOADING_ICON = "INSTANCE_LOADING_ICON";
